steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/agnost-ai/cloud-run-source-deploy/agnost-backend:latest
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - us-central1-docker.pkg.dev/agnost-ai/cloud-run-source-deploy/agnost-backend:latest

images:
  - us-central1-docker.pkg.dev/agnost-ai/cloud-run-source-deploy/agnost-backend:latest
